### ISSUE TITLE
Special Management for LAN/WAN

### ISSUE THREAD

**Issue by Laura7089** [FragSoc/esports-bot#17]
The LAN/WAN section on the fragsoc server is hidden by default, unhidden when we are running a LAN/WAN event. The bot should automatically (or upon issuing a command) unhide/hide this at the appropriate times.
The signin channel should be reset, with the LAN/WAN role being removed from everyone and requiring them to sign in for each weekend.

**Comment by Trimatix** [comment]
Implemented: https://github.com/Trimatix/Esports-Bot-Rewrite/tree/auto-LAN
