### ISSUE TITLE
Solve concurrent access in MusicCog.check_active_channels

### ISSUE THREAD

**Issue by Trimatix** [FragSoc/esports-bot#46]
possibly with a mutex

_Originally posted by @Trimatix in https://github.com/FragSoc/esports-bot/pull/28#discussion_r607367966_

**Comment by Trimatix** [comment]
Marking this as won't fix following Fux's improvement over this with key set copying rather than entire dictionary copying, a big improvement

**Comment by Laura7089** [comment]
Perhaps close this issue?
