### ISSUE TITLE
re-enable d.py stock help command

### ISSUE THREAD

**Issue by Trimatix** [FragSoc/esports-bot#78]

**Comment by Laura7089** [comment]
Why did we disable the stock help command?

**Comment by Laura7089** [comment]
From @Ryth-cs :
> Standard help command was removed at the start of development. Can be turned back on or for someone to write a custom one.
Can we just re-enable it to have it pull the help strings from all our registered commands with the bot?

**Comment by Trimatix** [comment]
As long as the help strings are registered through the command decorator it should work out of the box (and was working at one point)

**Comment by Trimatix** [comment]
Meeting notes: Revert disabling of help command
