### ISSUE TITLE
Formal minimum dependencies versions?

### ISSUE THREAD

**Issue by Laura7089** [FragSoc/esports-bot#82]
I'm pretty sure the bot needs at least python `3.8`, but I'm not too sure about that. We should formalise this.

**Comment by Laura7089** [comment]
We probably also want to formalise the minimum versions of `docker`, `docker-compose` and `postgres` too while we're at it.

**Comment by Fluxticks** [comment]
Yeah the postgres one is an important one. I know that it definitely doesn't work on postgres 9, as I found that out the annoying way.

**Comment by Laura7089** [comment]
These can just be as easy as looking at what versions we know work, decide if we think we should test older versions (if they're pre-release versions or whatever) then just adding a little "Minimum X Version: x.x.x" badge to the README, and version tags to docker-related files.

**Comment by Fluxticks** [comment]
Not sure if this would come under the same issue, but there should also be a list of permissions the bot needs from discord, and we could even provide the unique code/id for that combination of permissions.

**Comment by Laura7089** [comment]
Regarding software versions, we could probably just set them to the latest stable versions that we're using, ie:

Python 3.8+
Postgres 11+
Docker 20+
docker-compose version 1.25+

**Comment by Laura7089** [comment]
> 
> 
> Not sure if this would come under the same issue, but there should also be a list of permissions the bot needs from discord, and we could even provide the unique code/id for that combination of permissions.

Probably wants it's own issue.
